const C_TYPE = {
  EMPTY_BASE: 0,
  EMPTY_STAR: 1,
  EMPTY_STAR_LIGHT: 2,

  SAND_BASE: 3,
  SAND_LIGHT: 4,
  SAND_DARK: 5,

  WATER_BASE: 6,
  WATER_LIGHT: 7,
  WATER_DARK: 8,

  DIRT_BASE: 9,
  DIRT_LIGHT: 10,
  DIRT_DARK: 11,

  LAVA_BASE: 12,
  LAVA_GLOW: 13,
  LAVA_DARK: 14,

  STONE_BASE: 15,
  STONE_LIGHT: 16,
  STONE_DARK: 17,

  GRASS_BASE: 18,
  GRASS_LIGHT: 19,
  GRASS_DARK: 20,

  TREE_FOLIAGE: 21,
  TREE_TRUNK: 22,
  TREE_HIGHLIGHT: 23,
  TREE_SHADOW: 24,

  ANIMAL_BASE: 25,
  ANIMAL_SHADOW: 26,
  ANIMAL_DETAIL: 27,

  FLOWER_BASE: 28,
  FLOWER_CENTER: 29,
  FLOWER_PINK: 30,

  FISH_BASE: 31,
  FISH_LIGHT: 32,
  FISH_DARK: 33,
};

const PARTICLE_COLORS = {
  [C_TYPE.EMPTY_BASE]: '#0A0E1A',
  [C_TYPE.EMPTY_STAR]: '#bceaf2',
  [C_TYPE.EMPTY_STAR_LIGHT]: '#FFFFFF',

  [C_TYPE.SAND_BASE]: '#E2B76D',
  [C_TYPE.SAND_LIGHT]: '#F5D598',
  [C_TYPE.SAND_DARK]: '#C1964A',

  [C_TYPE.WATER_BASE]: '#1E90FF',
  [C_TYPE.WATER_LIGHT]: '#4FB9FF',
  [C_TYPE.WATER_DARK]: '#1461A0',

  [C_TYPE.DIRT_BASE]: '#6B4226',
  [C_TYPE.DIRT_LIGHT]: '#8D5B34',
  [C_TYPE.DIRT_DARK]: '#4A2D1A',

  [C_TYPE.LAVA_BASE]: '#FF4500',
  [C_TYPE.LAVA_GLOW]: '#FF8C42',
  [C_TYPE.LAVA_DARK]: '#992800',

  [C_TYPE.STONE_BASE]: '#8B8C8E',
  [C_TYPE.STONE_LIGHT]: '#B7B8BA',
  [C_TYPE.STONE_DARK]: '#5A5B5D',

  [C_TYPE.GRASS_BASE]: '#3FA34D',
  [C_TYPE.GRASS_LIGHT]: '#64C264',
  [C_TYPE.GRASS_DARK]: '#2A7133',

  [C_TYPE.TREE_FOLIAGE]: '#2D6A33',
  [C_TYPE.TREE_TRUNK]: '#7B4C20',
  [C_TYPE.TREE_HIGHLIGHT]: '#4F9435',
  [C_TYPE.TREE_SHADOW]: '#1D3F1B',

  [C_TYPE.ANIMAL_BASE]: '#FFEFD5',
  [C_TYPE.ANIMAL_SHADOW]: '#D6C7B0',
  [C_TYPE.ANIMAL_DETAIL]: '#9A8F84',

  [C_TYPE.FLOWER_BASE]: '#FFFFFF',
  [C_TYPE.FLOWER_CENTER]: '#FFD700',
  [C_TYPE.FLOWER_PINK]: '#FF69B4',

  [C_TYPE.FISH_BASE]: '#7EC8E3',
  [C_TYPE.FISH_LIGHT]: '#B3E6FF',
  [C_TYPE.FISH_DARK]: '#2A6E88',
};
